; VARIABLES

ptr_0 = $0000
ptr_1 = $0001 

data_2 = $0002
data_3 = $0003 

byte_4 = $0004

tilemapData_4C = $004C
roomUnk1_4D = $004D
roomUnk2_4E = $004E
tilemap_line_idx_4F = $004F 
mapLineSize_50 = $0050
tilemap_line_size_51 = $0051 
mapLineWidth_52 = $0052
mapLineHeight_53 = $0053 
byte_56 = $0056  
byte_5C = $005C 

bank_switch_flag_6C = $006C
ppu_fld0_x_6D = $006D
ppu_fld1_y_6E = $006E
has_ppu_data_to_upload_6F = $006F

ppu_data_70 = $0070

apu_unk_FE = $00FE
apu_unk_FF = $00FF